<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4823dc4e7cc0120d1bed9810cabc6bb2
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PhpOffice\\PhpPresentation\\' => 26,
            'PhpOffice\\Common\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PhpOffice\\PhpPresentation\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpoffice/phppresentation/src/PhpPresentation',
        ),
        'PhpOffice\\Common\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpoffice/common/src/Common',
        ),
    );

    public static $classMap = array (
        'PclZip' => __DIR__ . '/..' . '/pclzip/pclzip/pclzip.lib.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4823dc4e7cc0120d1bed9810cabc6bb2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4823dc4e7cc0120d1bed9810cabc6bb2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4823dc4e7cc0120d1bed9810cabc6bb2::$classMap;

        }, null, ClassLoader::class);
    }
}
